# Generated by Django 3.1.7 on 2021-03-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanuló',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('név', models.CharField(max_length=30)),
                ('om', models.IntegerField()),
                ('a', models.BooleanField(max_length=30)),
                ('b', models.BooleanField(max_length=30)),
                ('c', models.BooleanField(max_length=30)),
                ('d', models.BooleanField(max_length=30)),
                ('e', models.BooleanField(max_length=30)),
                ('f', models.BooleanField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tanuló',
                'verbose_name_plural': 'Tanulók',
            },
        ),
    ]
