# Generated by Django 3.1.7 on 2021-03-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felvevo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanuló',
            name='a',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tanuló',
            name='b',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tanuló',
            name='c',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tanuló',
            name='d',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tanuló',
            name='e',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tanuló',
            name='f',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tanuló',
            name='om',
            field=models.CharField(max_length=11),
        ),
    ]
