# Generated by Django 3.1.7 on 2021-03-10 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('felvevo', '0002_auto_20210309_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanuló',
            name='a',
        ),
        migrations.RemoveField(
            model_name='tanuló',
            name='b',
        ),
        migrations.RemoveField(
            model_name='tanuló',
            name='c',
        ),
        migrations.RemoveField(
            model_name='tanuló',
            name='d',
        ),
        migrations.RemoveField(
            model_name='tanuló',
            name='e',
        ),
        migrations.RemoveField(
            model_name='tanuló',
            name='f',
        ),
        migrations.AddField(
            model_name='tanuló',
            name='felveve',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanuló',
            name='szak',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
