# Generated by Django 3.1.7 on 2021-04-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felvevo', '0005_auto_20210310_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arucikk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(default='', max_length=128)),
                ('db', models.IntegerField(default=0)),
                ('mertekegyseg', models.CharField(default='', max_length=128)),
            ],
            options={
                'verbose_name': 'Áru',
                'verbose_name_plural': 'Áruk',
            },
        ),
        migrations.DeleteModel(
            name='Tanuló',
        ),
    ]
